# vim: filetype=dockerfile
FROM xiejw/tex

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        pandoc \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /source

CMD ["bash"]
