# vim: filetype=dockerfile

# Clang-format 9.0 is only available in new Debian.
# FROM xiejw/baseimage
FROM debian:bullseye-slim

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        clang-format \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY clang-format.sh /
COPY clang-format.config /.clang-format

WORKDIR /workdir

CMD ["bash"]
