# vim: filetype=dockerfile
FROM xiejw/ubuntu

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        wget \
        perl-tk \
        python \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /profiles/ \
    && mkdir -p /source

COPY assets/texlive.profile /profiles/

ENV TEXLIVE_INSTALL_TEXDIR=/usr/local/texlive
ENV PATH /usr/local/texlive/bin/x86_64-linux:$PATH

RUN wget http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz \
	  && tar -zxf install-tl-unx.tar.gz \
    && cd install-tl-*/ \
	  && ./install-tl --profile=/profiles/texlive.profile \
    && cd / \
    && rm -rf install*

WORKDIR /source

CMD ["bash"]
