# vim: filetype=dockerfile

FROM xiejw/baseimage

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        openssh-server mpich \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

WORKDIR /workdir

CMD ["bash"]
