# vim: filetype=dockerfile
FROM xiejw/baseimage

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        ghc \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workdir

CMD ["bash"]
